#include <pebble.h>

#define _TICK_INSETS_RECT 26
#define _TICK_INSETS_ROUND 30
#define _TICK_INSETS_RECT_LARGE 30

#if PBL_DISPLAY_HEIGHT == 228
  #define TICK_INSETS _TICK_INSETS_RECT_LARGE
#elif defined(PBL_ROUND)
  #define TICK_INSETS _TICK_INSETS_ROUND
#else
  #define TICK_INSETS _TICK_INSETS_RECT
#endif


#define _HAND_WIDTH 5
#define _HAND_WIDTH_HIDPI 7

#define HAND_WIDTH (PBL_DISPLAY_HEIGHT == 228 ? _HAND_WIDTH_HIDPI : _HAND_WIDTH)


#define _SEC_WIDTH 2
#define _SEC_WIDTH_HIDPI 3

#define SEC_WIDTH (PBL_DISPLAY_HEIGHT == 228 ? _SEC_WIDTH_HIDPI : _SEC_WIDTH)


#define _HOUR_MARK_WIDTH 3
#define _HOUR_MARK_WIDTH_HIDPI 5

#define HOUR_MARK_WIDTH (PBL_DISPLAY_HEIGHT == 228 ? _HOUR_MARK_WIDTH_HIDPI : _HOUR_MARK_WIDTH)

#define _MINUTE_MARK_WIDTH 1
#define _MINUTE_MARK_WIDTH_HIDPI 3

#define MINUTE_MARK_WIDTH (PBL_DISPLAY_HEIGHT == 228 ? _MINUTE_MARK_WIDTH_HIDPI : _MINUTE_MARK_WIDTH)


#define _HAND_INSET_RECT 10
#define _HAND_INSET_ROUND 30
#define _HAND_INSET_RECT_LARGE 15

#if PBL_DISPLAY_HEIGHT == 228
  #define HAND_INSET _HAND_INSET_RECT_LARGE
#elif defined(PBL_ROUND)
  #define HAND_INSET _HAND_INSET_ROUND
#else
  #define HAND_INSET _HAND_INSET_RECT
#endif

#define _WORDMARK_FONT FONT_KEY_GOTHIC_14_BOLD
#define _WORDMARK_FONT_HIDPI FONT_KEY_GOTHIC_18_BOLD
 #define WORDMARK_FONT (PBL_DISPLAY_HEIGHT == 228 ? _WORDMARK_FONT_HIDPI : _WORDMARK_FONT)